### ISSUE TITLE
icons don't appear to work inside YAML of rmarkdown?

### ISSUE THREAD

**Issue by njtierney** [mitchelloharawild/icons#60]
Hello!

I feel like we have talked about this in the past, so my apologies if this has already been solved.

When I have a xaringan presentation with YAML like so:

```
---
title: title
author: me
date: "<div class='medium'>Event, <br><br> `r icons::fontawesome(name = 'link', 'solid')` **bit.ly/LINK** <br><br> `r icons::fontawesome$brands$twitter` **HANLDE**</div>"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: 
      - njtheme.css
      - extra.css
      - animate.css
      - typewriter.css
    nature:
      ratio: "16:9"
      titleSlideClass: ["left", "middle", "inverse"]
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: "%current%"  
---
```

When I knit the presentation I get

```
output file: index.knit.md

Error in yaml::yaml.load(..., eval.expr = TRUE) : 
  Parser error: while parsing a block mapping at line 1, column 1 did not find expected key at line 3, column 61
Calls: <Anonymous> ... parse_yaml_front_matter -> yaml_load -> <Anonymous>
Execution halted
```

I was wondering if there is a workaround for this?
